services:
  postgres:
    image: postgres:17-alpine
    container_name: ibook_postgres
    env_file: ".env"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
